name: Build and Deploy Code

on:
  push:
    branches: 
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hello
        run: "echo PM\n\n"